### ISSUE TITLE
Mandatory arguments marked as optional

### ISSUE THREAD

**Issue by tian2992** [devgateway/jocds#16]
Hello! 
a minor issue, tried to use the validator's /api/validateJsonUrl, on the data type model tab, the arguments are marked as optional, however at least `url` and `schemaType` are mandatory. Looking at the other endpoints, all arguments seem to be marked as optional. Can you share how this can be marked properly please?

Cheers!

**Comment by mpostelnicu** [comment]
hi, @tian2992 thanks for the feedback. im checking this!
